version: "3.2"

services: 
    # http://localhost:8080/
    restsimulator :
        container_name: restsimulator
        hostname: restsimulator
        image: jetty:9.4-jre11
        networks:
            service_tier:
                aliases:
                - restsimulator
        ports: 
        - "8080:8080"
        volumes:
        - ./target/com619-devops-project-ae1-0.0.1-SNAPSHOT.war:/var/lib/jetty/webapps/root.war
            
    nginxserver :
        container_name: nginxserver
        hostname: nginxserver
        image: nginx:latest
        networks:
            service_tier:
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
    service_tier:
        name: service_tier